admingenerator_generator:
    # choose only one
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false
    # choose and uncomment only one
    base_admin_template: AdmingeneratorGeneratorBundle::base_admin.html.twig   