fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\UserBundle\Entity\User
    
    from_email:
        address:        contact@symfony2-distribution.com
        sender_name:    kadala