fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\UserBundle\Entity\User

    from_email:
        address:        contact@symfonybricks.com
        sender_name:    SymfonyBricks.com

    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        confirmation:
            enabled:    true
            template:   ApplicationUserBundle:Registration:registration.email.twig

    resetting:
        email:
            template:   ApplicationUserBundle:Resetting:resetting.email.twig

    profile:
        form:
            type: application_user_profile