# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%java_path%"
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        stylesheets:
            inputs:
                - "%kernel.root_dir%/../web/assets/bootstrap-2.3.2/dist/css/bootstrap.min.css"
            filters: [?yui_css, cssrewrite]

        javascripts_header:
            inputs:
                - "%kernel.root_dir%/../web/assets/jquery/jquery-1.8.2.js"
            filters: [?yui_js, cssrewrite]

        javascripts_footer:
            inputs:
                - "%kernel.root_dir%/../web/assets/bootstrap-2.3.2/dist/js/bootstrap.min.js"

            filters: [?yui_js, cssrewrite]