####################################################################################################################
# Configuration file for translations and locales                                                                  #
####################################################################################################################

parameters:

    locale:   en #default locale
        
    # parameter to be used in routes.yml
    # add |[locale] if a new interface locale is available
    route_locale_requirements: '^it|en|es$'