security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/

            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login 
                check_path:     fos_user_security_check

            oauth:
                resource_owners:
                    github:             "/login/check-github"
                    twitter:            "/login/check-twitter"
                    sensiolabsconnect:  "/login/check-sensiolabsconnect"
                login_path:   /login
                failure_path: /login

                oauth_user_provider:
                    service: application.user_provider

            logout:
                path:   logout
                target: /

            anonymous:    true

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^(/(%route_locale_requirements%)/login)|(/login)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/(%route_locale_requirements%)/user/, role: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN