# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: 
            - ROLE_ADMIN
            - ROLE_USER_ADMIN_USERS
            - ROLE_FORUM_MODERATE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
         main:
            pattern:         ^/
            form_login:
                provider:    fos_userbundle
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
                csrf_provider:  form.csrf_provider
                
            remember_me:
                key:         "%secret%"
                lifetime:    3600
                path:        /
                
            logout:
                path:        fos_user_security_logout
                target:      /
                
            anonymous:       true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }